### ISSUE TITLE
CI steps need to be enhanced to incorporate a more e2e validation

### ISSUE THREAD

**Issue by ashutshkumr** [openconfig/kne#141]
Every time a collaborator makes a change in KNE, apart from unit test results, there's no other way for them to have confidence on whether something broke.

At very minimum, actions CI should include following:
- Deploy at least one topology consisting of each node type
- Deploy topology with some variations (e.g. grouped interfaces, back-to-back interfaces, etc.)
- Deploy topology with negative use cases (e.g. duplicate interface name per node, duplicate group name, duplicate node name, non-existent vendor, etc.)

It would be nice to include following validations post deployment as part of CI:
- meshnet CRD is correct
- services exposed are appropriately reachable (socket connection check)
- output of KNE topology doesn't break ONDATRA's reservation logic

My initial suggestion would be to trigger these `on-pull-request` and not `on-push`.

**Comment by alexmasi** [comment]
First step toward a more end to end presubmit: https://github.com/openconfig/kne/pull/215
