### ISSUE TITLE
Cannot connect to routers with host name that do not match a certain regexp

### ISSUE THREAD

**Issue by jinsun-yoo** [openconfig/kne#163]
Scrapli cannot establish connection with routers whose client hostname does not match a certain regexp

When establishing a connection with a router ([WaitCliReady](https://github.com/openconfig/kne/blob/d165a4abf1204e1c4b4577cd7670b1a44679e450/topo/node/cptx/cptx.go#L81)), scrapli tries to look for the command prompt by running the client's message through a regular expression ([scrapli link](https://github.com/scrapli/scrapligo/blob/40ed54b60468d8c3867561598a9b8f55f590b511/channel/getprompt.go#L29)). For example, scrapli is looking for the message in the red box in the picture below. 

![image](https://user-images.githubusercontent.com/38969914/178045240-79406b07-bdfd-402e-b4d2-b02a7c0db18b.png)

If the hostname does not match the regular expression, from scrapli's perspective, the client never issued the command prompt, and scrapli will hang infinitely until it "sees" the command prompt. 
Specifically, in my case, `root@testname>` would successfully match the expression, but `root@test.name>` would not. 

The regular expression is hardcoded in scrapli, and cannot be fixed from this reposity. ([Pattern Link](https://github.com/scrapli/scrapligo/blob/40ed54b60468d8c3867561598a9b8f55f590b511/driver/core/juniperjunos.go#L15))

**Comment by hellt** [comment]
Hi @jinsun-yoo 

on a related note, if you are deep into junos, can you check if this regexp answers the needs of the exec prompt pattern?
I added the missing dot char in the second portion, but it would be good if someone who knows most common prompts vet this
https://regex101.com/r/S26huc/1

**Comment by jinsun-yoo** [comment]
> Hi @jinsun-yoo
> 
> on a related note, if you are deep into junos, can you check if this regexp answers the needs of the exec prompt pattern? I added the missing dot char in the second portion, but it would be good if someone who knows most common prompts vet this https://regex101.com/r/S26huc/1

Hi @hellt , 
I am not familiar with junos in general, but adding the dot char would satisfy my current usecase. Thank you for your help!

**Comment by carlmontanari** [comment]
Hey ya'll -- I think @hellt has a goal of updating kne to use the fresh scrapligo 1.x.x train at some point, but until then we can fix this issue in kne like:

```go
       privLevels := map[string]*base.PrivilegeLevel{
		"exec": {
			Pattern:        `(?im)^({\w+:\d}\n){0,1}[\w\-@()/:]{1,63}>\s?$`,
			Name:           execPrivLevel,
			PreviousPriv:   "",
			Deescalate:     "",
			Escalate:       "",
			EscalateAuth:   false,
			EscalatePrompt: "",
		},
		"configuration": {
			Pattern:        `(?im)^({\w+:\d}\[edit\]\n){0,1}[\w\-@()/:]{1,63}#\s?$`,
			Name:           configPrivLevel,
			PreviousPriv:   execPrivLevel,
			Deescalate:     "exit configuration-mode",
			Escalate:       "configure",
			EscalateAuth:   false,
			EscalatePrompt: "",
		},
		"configuration_exclusive": {
			Pattern:        `(?im)^({\w+:\d}\[edit\]\n){0,1}[\w\-@()/:]{1,63}#\s?$`,
			Name:           "configuration_exclusive",
			PreviousPriv:   execPrivLevel,
			Deescalate:     "exit configuration-mode",
			Escalate:       "configure exclusive",
			EscalateAuth:   false,
			EscalatePrompt: "",
		},
		"configuration_private": {
			Pattern:        `(?im)^({\w+:\d}\[edit\]\n){0,1}[\w\-@()/:]{1,63}#\s?$`,
			Name:           "configuration_private",
			PreviousPriv:   execPrivLevel,
			Deescalate:     "exit configuration-mode",
			Escalate:       "configure exclusive",
			EscalateAuth:   false,
			EscalatePrompt: "",
		},
		"shell": {
			Pattern:            `(?im)^.*[%$]\s?$`,
			PatternNotContains: []string{"root"},
			Name:               "shell",
			PreviousPriv:       execPrivLevel,
			Deescalate:         "exit",
			Escalate:           "start shell",
			EscalateAuth:       false,
			EscalatePrompt:     "",
		},
		"root_shell": {
			Pattern:        `(?im)^.*root@[[:ascii:]]*?:?[[:ascii:]]*?[%#]\s?$`,
			Name:           "root_shell",
			PreviousPriv:   execPrivLevel,
			Deescalate:     "exit",
			Escalate:       "start shell user root",
			EscalateAuth:   true,
			EscalatePrompt: `(?im)^[pP]assword:\s?$`,
		},
	}

	d, err := scraplicore.NewCoreDriver(
		n.Name(),
		"juniper_junos",
		scraplibase.WithAuthBypass(true),
		// disable transport timeout
		scraplibase.WithTimeoutTransport(0),
		scraplibase.WithTimeoutOps(scrapliOperationTimeout),
                // replace default privilege levels to include expanded prompt pattern
                scraplibase.WithPrivilegeLevels(privLevels),
	)
```

The above bits would go [here](https://github.com/openconfig/kne/blob/main/topo/node/cptx/cptx.go#L113-L120) and of course expand the patterns to include the period wherever necessary (above priv levels are just copy/pasta from v0.1.3 Junos platform)

HTH!

Carl

**Comment by jinsun-yoo** [comment]
Hi @carlmontanari thank you for the suggestion! Yest that sounds like a very doable/effective solution for the time being :)

**Comment by hellt** [comment]
I'm working on updating kne to use scrapligo v1, and there we don't have to deal with that issue anymore, as the regexps have been fixed upstream

**Comment by alexmasi** [comment]
https://github.com/openconfig/kne/pull/165
