### ISSUE TITLE
Need support for using gRPC (instead of VXLAN) meshnet link between pods deployed on separate nodes

### ISSUE THREAD

**Issue by ashutshkumr** [openconfig/kne#202]
As of https://github.com/networkop/meshnet-cni/commit/f26c1934ec3a66c33a43cbdba57e1ccb01993bb4, one can now opt-in to use gRPC link between pods deployed on separate nodes, like so:

```sh
git clone https://github.com/networkop/meshnet-cni.git
cd meshnet-cni && kubectl apply -k manifests/overlays/grpc-link
```

`kne_cli deploy` should anchor to the commit noted above and expose a configurable option to switch between VXLAN and gRPC link, until latter is stable enough to be used as a default.

@kingshukdev FYI

**Comment by alexmasi** [comment]
https://github.com/openconfig/kne/pull/278
