### ISSUE TITLE
Pods in pending state

### ISSUE THREAD

**Issue by jasrikmsft** [openconfig/kne#285]
I installed kne as per document and tried to deploy nokia 2srl-certs topology. It has been on pending state for 15 minutes. am i missing something? this is the message i get;

INFO[0002] Node "r2" resource created
INFO[0002] r1 - generating self signed certs
INFO[0002] r1 - waiting for pod to be running

**Comment by alexmasi** [comment]
Not sure if you have already but I would suggest taking a look at the troubleshooting guide: https://github.com/openconfig/kne/blob/main/docs/troubleshoot.md

If you cannot find a solution after going through that guide then please post more details (the pod logs, etc.)

**Comment by jasrikmsft** [comment]
Thank you. checked the logs and it was insufficient cpu. deleted some namespaces and worked fine.

Is there any other documentation available? which are the vendors supported right now? can we get the container image from any vendor and deploy through kne?

**Comment by alexmasi** [comment]
the examples dir show examples with other vendors: https://github.com/openconfig/kne/tree/main/examples

currently we support cisco, arista, nokia, and juniper (along with keysight ixia for traffic gen)

you'll have to reach out to each vendor to access their containers (besides nokia which the un-licensed version is open sourced)

**Comment by jasrikmsft** [comment]
Hi Alex,

   Thanks for the response.

   I am trying to create a topoogy for the arista device from exaples folder and getting the following error. Looks like access denied error while accessing the container. I created an user account in arista portal. How do i fix this access error?

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  97s                default-scheduler  Successfully assigned ceos/r1 to kne-control-plane
  Normal   Pulled     97s                kubelet            Container image "networkop/init-wait:latest" already present on machine
  Normal   Created    97s                kubelet            Created container init-r1
  Normal   Started    97s                kubelet            Started container init-r1
  Normal   Pulling    41s (x3 over 82s)  kubelet            Pulling image "ceos:latest"
  Warning  Failed     40s (x3 over 80s)  kubelet            Failed to pull image "ceos:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/ceos:latest": failed to resolve reference "docker.io/library/ceos:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     40s (x3 over 80s)  kubelet            Error: ErrImagePull
  Normal   BackOff    12s (x3 over 56s)  kubelet            Back-off pulling image "ceos:latest"
  Warning  Failed     12s (x3 over 56s)  kubelet            Error: ImagePullBackOff

Thanks,
Jaya


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by alexmasi** [comment]
This error message is indicating that `ceos:latest` cannot be found on dockerhub. You'll have to first `docker pull` the image from arista's portal and then load it into the kind cluster as `ceos:latest`. See the docs here: https://github.com/openconfig/kne/blob/main/docs/create_topology.md#container-images
