### ISSUE TITLE
Incorrect image path for ixia-c-operator in `ixiatg-operator.yaml`

### ISSUE THREAD

**Issue by bortok** [openconfig/kne#295]
Operator manifest for `IxiaTG`: [`manifests/keysight/ixiatg-operator.yaml`](../blob/main/manifests/keysight/ixiatg-operator.yaml#L390) currently points to:
```
image: ghcr.io/open-traffic-generator/licensed/ixia-c-operator:0.3.1
```

while correct path is w/o "licensed":
```
image: ghcr.io/open-traffic-generator/ixia-c-operator:0.3.1
```

**Comment by alexmasi** [comment]
Good catch, fixed
