### ISSUE TITLE
Image for ixia-c-controller has moved

### ISSUE THREAD

**Issue by emilykmarx** [openconfig/kne#332]
The path to `ixia-c-controller` in [`manifests/keysight/ixiatg-configmap.yaml`](https://github.com/openconfig/kne/blob/101a679d234bef62b39bd90c109a701886bb2b40/manifests/keysight/ixiatg-configmap.yaml#L13) is currently 

`ghcr.io/open-traffic-generator/licensed/ixia-c-controller`, 

but the image looks to have moved to 

`ghcr.io/open-traffic-generator/ixia-c-controller`

(Similar to https://github.com/openconfig/kne/issues/295)

**Comment by alexmasi** [comment]
keysight has licensed and un-licensed versions of the controller and protocol-engine containers, these have different capabilities AFAIK

you can either reach out to keysight for access or you can remove the licensed/ piece of the path for both images to get something up an running

sorry for the confusion, I will add a section to the docs about this and consider omitting the licensed/ piece of the path for future version imports

**Comment by alexmasi** [comment]
We now have an "unlicensed" deployment file that only uses public images: https://github.com/openconfig/kne/blob/bed949c023f5278ba991a86670a3ffb607f6924d/deploy/kne/kind-bridge-unlicensed.yaml#L27
