### ISSUE TITLE
External-IP access

### ISSUE THREAD

**Issue by yennym3** [openconfig/kne#384]
I am trying to access from an external host to the services through its EXTERNAL IP but I can't, how could I access these services outside the host where the topology is deployed?

![image](https://github.com/openconfig/kne/assets/74870040/e882d402-a1af-412e-baca-97a8e2b23bb7)

**Comment by alexmasi** [comment]
These IPs are external to the cluster, so from the host on which the cluster is deployed they can be accessed. As far as from a different host from the one running the cluster you'd have to somehow expose those using a forwarding table or something
