### ISSUE TITLE
Add timeout as for kne deploy

### ISSUE THREAD

**Issue by arkajyoti-cloud** [openconfig/kne#386]
During kne deploy kne/deploy/kne/kind-bridge.yaml, sometimes due to slowness it gets timed out. At present there is a no way to provide a timeout value. please provide that.

**Comment by alexmasi** [comment]
Are you referring to the timeout to wait for a resource to be healthy? https://github.com/openconfig/kne/blob/e7d9c854d625d74cd1406a197279538078b0bcdb/deploy/deploy.go#L82

I would accept a contribution to add a flag value to configure this for `kne deploy` although I believe the current 1 minute should suffice for most clusters.
