### ISSUE TITLE
Error no adress pooling when deploy external-compose

### ISSUE THREAD

**Issue by hecko21** [openconfig/kne#394]
Cluster version: 1.27
CNI: Flannel up-to-date and working
All nodes are working and i can deploy anything in the cluster and workers.
The hairpin mode is enable in the flannel config.
I have not an ingress controller but i don't see anything in the guide set-up.
I have CRI (Dockerd, plugin of mirantis and docker)

After do an apply, i got the issue about can't route to host as i shown in the image:
![image](https://github.com/openconfig/kne/assets/121292624/767526bb-fa0a-4aa2-8f4a-e8b4157e63f9)

Bonus: If i ignore all failurePolicy of the webhookconfiguration or if i delete it and create the metal-lb indepent of the deploy of external-compose.yaml i can deploy all the controllers and cni in the file but it doesnt deploy in the right network and keep everytime in init and the host get in the status: Error.

**Comment by alexmasi** [comment]
MetalLB creates the address pool from a docker network, the name of this pool should be specified in the deployment config: https://github.com/openconfig/kne/blob/1d7c895f753a9c6cf4a6b4b7b286daa833322cda/deploy/kne/external-multinode.yaml#L7

this network is created in the codelab: https://github.com/openconfig/kne/blob/1d7c895f753a9c6cf4a6b4b7b286daa833322cda/deploy/kne/external-multinode.yaml#L7

Not sure exactly the commands you've run to repro this issue, hopefully that helps

**Comment by hecko21** [comment]
> MetalLB creates the address pool from a docker network, the name of this pool should be specified in the deployment config:
> 
> https://github.com/openconfig/kne/blob/1d7c895f753a9c6cf4a6b4b7b286daa833322cda/deploy/kne/external-multinode.yaml#L7
> 
> this network is created in the codelab:
> 
> https://github.com/openconfig/kne/blob/1d7c895f753a9c6cf4a6b4b7b286daa833322cda/deploy/kne/external-multinode.yaml#L7
> 
> Not sure exactly the commands you've run to repro this issue, hopefully that helps

Good morning Alex,

I'm doing the command: kne deploy /path/to/file/external-multinode.yaml,
![image](https://github.com/openconfig/kne/assets/121292624/c91fc96f-1b2f-47fc-bad9-2789e3f52d4f)
it was wrote in the top of the file and im getting the same issue.
![image](https://github.com/openconfig/kne/assets/121292624/d53533d9-08ec-4a0b-9e63-d0c50ccd98c5)

After do command im getting the same but a bit different and now i'm getting connection refused:
![image](https://github.com/openconfig/kne/assets/121292624/50555990-85f2-4f70-83d8-b66db8ae781a)

i want to keep in mind that i'm using as CRI-Dockerd  but when i don't create the network multinode, it displays an error of it doesnt reach the ipv4 docker net but after create, i got this error but if you inspect the network is 172.17.x.x (default) and 172.20.X.X (Multinode), and also appears that i have a replica of IPs with kube-proxy and enpoint of metallb:

![image](https://github.com/openconfig/kne/assets/121292624/90f821c5-9e35-4d8d-8883-9261486021de)

multinode:
![image](https://github.com/openconfig/kne/assets/121292624/97528bff-5165-4da1-9de1-bd9c9ad535a5)

bridge:
![image](https://github.com/openconfig/kne/assets/121292624/8691eb65-b5c5-4d8f-a4b6-ec7ede51771b)

I don't know why kne is using network bridge if i specify multinode.
