### ISSUE TITLE
Pod reset

### ISSUE THREAD

**Issue by yennym3** [openconfig/kne#410]
Hi,
If it happens that a pod is evicted from the node because it was running out of ephemeral storage resources, how can the pod be configured so that the pod can be restarted using kne

<img width="896" alt="image" src="https://github.com/openconfig/kne/assets/74870040/1735135f-a47d-4207-9bee-bc9ac3139ec2">

**Comment by alexmasi** [comment]
So in this case you were creating a kne `HOST` node with the `alpine:latest` container image. However when creating the topo, the k8 node did not have enough storage. But it appears the image was in fact later pulled (did the k8 node gain more resources? or is this using kind?). Then after the image was pulled the pod creation was never retried?

**Comment by yennym3** [comment]
> So in this case you were creating a kne `HOST` node with the `alpine:latest` container image. However when creating the topo, the k8 node did not have enough storage. But it appears the image was in fact later pulled (did the k8 node gain more resources? or is this using kind?). Then after the image was pulled the pod creation was never retried?

Yes, it pulls the image and creates the container, then kills the container, the pod goes to completed status, but does not try to create it again. 
<img width="956" alt="image" src="https://github.com/openconfig/kne/assets/74870040/2f377cbb-6c3b-4c43-bc04-7e63ac076a12">

> NAME      READY     STATUS               RESTARTS    AGE      IP       NODE                  
   server2   0/1   Completed    0                       17m    <none>   k8worker2

**Comment by yennym3** [comment]
> So in this case you were creating a kne `HOST` node with the `alpine:latest` container image. However when creating the topo, the k8 node did not have enough storage. But it appears the image was in fact later pulled (did the k8 node gain more resources? or is this using kind?). Then after the image was pulled the pod creation was never retried?

Sorry, it was solved by giving more disk storage resources on the k8s node.

I have another question I would like to ask you, kne allows you to add a new router (pod) to a scenario that was already deployed?  Without having to destroy or redeploy the previously created topology, making use of a multi-node cluster.

**Comment by alexmasi** [comment]
There is no way to do this currently. There may be some hacky way you can apply extra yaml to do this, but it is not supported in the kne cli.
