### ISSUE TITLE
Low rates of throughput cEOS

### ISSUE THREAD

**Issue by yennym3** [openconfig/kne#447]
Hi,

I am testing a topology with 10 cEOS (Arista) and regarding througput I am getting low rates over the scenario, has this been tested?, would you know what can be related to such a low througput?.

<img width="333" alt="image" src="https://github.com/openconfig/kne/assets/74870040/fdbba4f2-6446-4fbc-b646-d5354394f3f9">
<img width="335" alt="image" src="https://github.com/openconfig/kne/assets/74870040/f114f5b6-0dbd-404e-a47b-42c1938f5ba8">

**Comment by alexmasi** [comment]
I would check with Arista for ceos specific questions, we do not do any performance testing to validate KNE as a platform

**Comment by marcushines** [comment]
kne is never meant as a hardware replacement.  All forwarding is done in software.  What throughput are you expecting from a performance standpoint? for testing we are generally only looking for the order of 1000 packets per second per flow

**Comment by yennym3** [comment]
> kne is never meant as a hardware replacement. All forwarding is done in software. What throughput are you expecting from a performance standpoint? for testing we are generally only looking for the order of 1000 packets per second per flow

I have observed that the performance tends to decrease when the pods are hosted on different nodes. Ideally, we would like to achieve a throughput to 1 Gbps per second, for example.
